// Chip In HQ rate presets, job export and invoice references
const chipInBaseRenderSettings=renderSettings;
renderSettings=function(){chipInBaseRenderSettings();chipInNormaliseRateSettings();const host=$('#content');if(!host||$('#rateSettingsForm'))return;const section=document.createElement('div');section.innerHTML=`<div class="section-title"><div><h2>Job rates & references</h2><p>Default rates are used when a client does not have their own agreed rate.</p></div></div><form id="rateSettingsForm"><div class="card"><div class="form-grid"><div class="field"><label>Job reference prefix</label><input name="jobPrefix" value="${esc(state.settings.jobPrefix||'JOB')}"></div><div class="field"><label>Next job sequence</label><input name="nextJobNumber" type="number" min="1" value="${Number(state.settings.nextJobNumber||1)}"></div></div><div class="section-title"><div><h2>Category rate presets</h2></div></div><div class="table-wrap" style="box-shadow:none"><table style="min-width:520px"><thead><tr><th>Category</th><th>Hourly rate</th><th>Day rate</th></tr></thead><tbody>${CHIPIN_JOB_CATEGORIES.map(c=>{const r=state.settings.categoryRates[c]||{};return `<tr><td><strong>${esc(c)}</strong></td><td><div class="field"><input data-rate-cat="${esc(c)}" data-rate-type="hourly" type="number" min="0" step="0.01" value="${Number(r.hourly||0)||''}" placeholder="£"></div></td><td><div class="field"><input data-rate-cat="${esc(c)}" data-rate-type="day" type="number" min="0" step="0.01" value="${Number(r.day||0)||''}" placeholder="£"></div></td></tr>`}).join('')}</tbody></table></div><div class="form-actions"><button class="btn gold" type="submit">Save job rates</button></div></div></form>`;const gh=$('#ghCard'),danger=[...host.querySelectorAll('.section-title h2')].find(h=>h.textContent.trim()==='Danger zone')?.closest('.section-title');if(gh)gh.before(section);else if(danger)danger.before(section);else host.appendChild(section);$('#rateSettingsForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);state.settings.jobPrefix=String(fd.get('jobPrefix')||'JOB').trim()||'JOB';state.settings.nextJobNumber=Math.max(1,Number(fd.get('nextJobNumber')||1));$$('[data-rate-cat]',e.target).forEach(input=>{const c=input.dataset.rateCat,t=input.dataset.rateType;state.settings.categoryRates[c]=state.settings.categoryRates[c]||{hourly:0,day:0};state.settings.categoryRates[c][t]=Number(input.value||0)});await saveState();toast('Job rates saved')}};

const chipInBaseExportCSV=exportCSV;
exportCSV=function(type){if(type!=='jobs')return chipInBaseExportCSV(type);const rows=[['Reference','Customer ref / PO','Job','Client','Category','Start','End','Rate type','Rate','Hours','Minutes','Days','Discount','Override','Fee','Status','Description'],...state.jobs.map(j=>[j.reference,j.customerReference,j.title,clientById(j.clientId)?.name,j.category,j.startDate,j.endDate,j.rateType,j.rate,j.hours,j.minutes,j.days,j.discount,j.overrideAmount,j.amount,j.status,j.description])];downloadBlob(new Blob([makeCSV(rows)],{type:'text/csv;charset=utf-8'}),'jobs.csv')};

const chipInBaseOpenInvoiceForm=openInvoiceForm;
openInvoiceForm=function(id,jobId){chipInBaseOpenInvoiceForm(id,jobId);const form=$('#invoiceForm');if(!form)return;const inv=id?invoiceById(id):null,j=jobId?jobById(jobId):null,customerRef=inv?.customerReference||j?.customerReference||'',jobRef=inv?.jobReference||j?.reference||'';form.querySelector('.form-grid')?.insertAdjacentHTML('beforeend',`<div class="field"><label>Job reference</label><input name="jobReference" value="${esc(jobRef)}" placeholder="Optional"></div><div class="field"><label>Customer reference / Purchase Order</label><input name="customerReference" value="${esc(customerRef)}" placeholder="Optional"></div>`)};
const chipInBaseInvoicePreviewHTML=invoicePreviewHTML;
invoicePreviewHTML=function(inv){const html=chipInBaseInvoicePreviewHTML(inv),bits=[];if(inv.jobReference)bits.push(`<span><strong>Job ref:</strong> ${esc(inv.jobReference)}</span>`);if(inv.customerReference)bits.push(`<span><strong>Customer ref / PO:</strong> ${esc(inv.customerReference)}</span>`);return bits.length?html.replace('<div class="invoice-parties">',`<div class="invoice-reference-strip">${bits.join('')}</div><div class="invoice-parties">`):html};

if(typeof pdfBlob==='function'){
  const chipInBasePdfBlob=pdfBlob;
  pdfBlob=function(inv){if(!inv.jobReference&&!inv.customerReference)return chipInBasePdfBlob(inv);if(!window.jspdf)throw Error('PDF library did not load.');const {jsPDF}=window.jspdf,d=new jsPDF({unit:'mm',format:'a4'}),snap=invoiceSnap(inv),s=snap.business,c=snap.client,t=invoiceTotals(inv);try{if(LOGO_PDF_DATA_URL)d.addImage(LOGO_PDF_DATA_URL,'PNG',15,13,58,17)}catch{}d.setTextColor(10,47,87);d.setFontSize(24);d.setFont(undefined,'bold');d.text('INVOICE',195,22,{align:'right'});d.setFontSize(9);d.setFont(undefined,'normal');d.setTextColor(95,102,116);d.text(inv.number,195,28,{align:'right'});d.text(`Issued ${fmtDate(inv.issueDate)}   Due ${fmtDate(inv.dueDate)}`,195,33,{align:'right'});const refs=[inv.jobReference?`Job ref: ${inv.jobReference}`:'',inv.customerReference?`Customer ref / PO: ${inv.customerReference}`:''].filter(Boolean).join('   ');if(refs)d.text(refs,195,38,{align:'right'});d.setDrawColor(220);d.line(15,43,195,43);d.setTextColor(23,32,51);d.setFont(undefined,'bold');d.text('FROM',15,52);d.text('BILL TO',110,52);d.setFont(undefined,'normal');d.text(`${s.legalName||''} trading as ${s.tradingName||'Chip In'}\n${s.address||''}\n${s.email||''}${s.phone?'\n'+s.phone:''}`,15,58,{maxWidth:80});d.text(`${c.name||''}${c.contact?'\n'+c.contact:''}${c.address?'\n'+c.address:''}${c.email?'\n'+c.email:''}`,110,58,{maxWidth:80});let y=91;d.setFillColor(244,246,250);d.rect(15,y,180,8,'F');d.setFont(undefined,'bold');d.text('Description',18,y+5.5);d.text('Qty',135,y+5.5,{align:'right'});d.text('Rate',165,y+5.5,{align:'right'});d.text('Amount',192,y+5.5,{align:'right'});d.setFont(undefined,'normal');y+=12;(inv.items||[]).forEach(x=>{const lines=d.splitTextToSize(x.description,105);d.text(lines,18,y);d.text(String(x.qty),135,y,{align:'right'});d.text(money(x.rate),165,y,{align:'right'});d.text(money(x.qty*x.rate),192,y,{align:'right'});y+=Math.max(8,lines.length*5+2)});y+=5;d.line(115,y,195,y);y+=7;d.text('Subtotal',145,y,{align:'right'});d.text(money(t.subtotal),192,y,{align:'right'});if(s.vatRegistered){y+=6;d.text(`VAT ${inv.vatRate}%`,145,y,{align:'right'});d.text(money(t.vat),192,y,{align:'right'})}y+=8;d.setFont(undefined,'bold');d.setFontSize(12);d.text('TOTAL',145,y,{align:'right'});d.text(money(t.total),192,y,{align:'right'});d.setFontSize(8.5);d.setFont(undefined,'normal');d.setTextColor(90,97,110);d.text(`Payment by bank transfer\nAccount name: ${s.bankName||''}\nSort code: ${s.sortCode||''}   Account number: ${s.accountNumber||''}`,15,260);if(inv.notes)d.text(d.splitTextToSize(inv.notes,75),110,260);return d.output('blob')}
}
