// Chip In HQ secure private GitHub storage
const DATA_REPO='ChipButt/ChipIn-Data', DATA_API=`https://api.github.com/repos/${DATA_REPO}`, CRED_KEY='chipin_github_cred_v1', KDF_ROUNDS=250000;
let ghToken='', ghPass='', ghUnlocked=false, ghStateSha='', ghTimer=null, ghBusy=false, ghStatus='Private storage locked';
const localSave=saveState, baseSettings=renderSettings, baseMarkSent=markInvoiceSent, baseDownloadReceipt=downloadReceipt, baseDownloadPDF=downloadInvoicePDF;
const enc=new TextEncoder(), dec=new TextDecoder();
const b64=b=>{let s='';for(let i=0;i<b.length;i+=32768)s+=String.fromCharCode(...b.subarray(i,i+32768));return btoa(s)};
const unb64=s=>{const x=atob(s||''),b=new Uint8Array(x.length);for(let i=0;i<x.length;i++)b[i]=x.charCodeAt(i);return b};
const rand=n=>{const b=new Uint8Array(n);crypto.getRandomValues(b);return b};
async function keyFor(pass,salt,use,rounds=KDF_ROUNDS){const m=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:rounds,hash:'SHA-256'},m,{name:'AES-GCM',length:256},false,[use])}
async function sealBytes(bytes,pass){const salt=rand(16),iv=rand(12),key=await keyFor(pass,salt,'encrypt'),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,bytes));return JSON.stringify({format:'ChipInEncrypted',v:1,rounds:KDF_ROUNDS,salt:b64(salt),iv:b64(iv),data:b64(ct)})}
async function openBytes(text,pass){const e=JSON.parse(text);if(e.format!=='ChipInEncrypted')throw Error('Encrypted Chip In file not recognised.');try{const key=await keyFor(pass,unb64(e.salt),'decrypt',Number(e.rounds||KDF_ROUNDS));return new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(e.iv)},key,unb64(e.data)))}catch{throw Error('Wrong Chip In HQ passphrase, or the encrypted file is damaged.')}}
const sealText=(s,p)=>sealBytes(enc.encode(s),p), openText=async(s,p)=>dec.decode(await openBytes(s,p));
async function hashBytes(b){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('')}
function useful(){return !!(state.settings?.setupComplete||state.clients?.length||state.jobs?.length||state.invoices?.length||state.expenses?.length||state.prepBlocks?.length||state.outgoings?.length)}
function setGhStatus(s,k=''){ghStatus=s;for(const id of ['ghSyncState','ghSettingsStatus']){const e=document.getElementById(id);if(e){e.textContent=s;e.dataset.kind=k}}}
function addGhBadge(){if(document.getElementById('ghSyncState'))return;const f=document.querySelector('.sidebar-foot');if(!f)return;const d=document.createElement('div');d.className='cloud-sync-state';d.id='ghSyncState';d.textContent=ghStatus;f.insertBefore(d,f.lastElementChild)}
async function api(path,opt={}){if(!ghToken)throw Error('Private storage is locked.');const r=await fetch(DATA_API+path,{...opt,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:`Bearer ${ghToken}`,...(opt.headers||{})}});if(r.status===404&&opt.allow404)return null;if(r.status===401||r.status===403)throw Error('GitHub rejected the Chip In token. Check that it is valid and restricted to ChipIn-Data with Contents read/write.');if(!r.ok)throw Error(`GitHub storage error ${r.status}: ${(await r.text()).slice(0,180)}`);return r.status===204?null:r.json()}
async function checkToken(token){const old=ghToken;ghToken=token;try{const r=await api('');if(r.full_name!==DATA_REPO||!r.private)throw Error('The token did not open the private ChipIn-Data repository.')}finally{ghToken=old}}
const toB64Text=s=>b64(enc.encode(s)), fromB64Text=s=>dec.decode(unb64((s||'').replace(/\n/g,'')));
async function getFile(path){const f=await api(`/contents/${path}?ref=main`,{allow404:true});return f?{sha:f.sha,text:fromB64Text(f.content)}:null}
async function putFile(path,text,msg,sha=''){const body={message:msg,content:toB64Text(text),branch:'main'};if(sha)body.sha=sha;return api(`/contents/${path}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
async function putEncrypted(path,bytes,msg){const old=await getFile(path);return putFile(path,await sealBytes(bytes,ghPass),msg,old?.sha||'')}
async function getEncrypted(path){const f=await getFile(path);return f?openBytes(f.text,ghPass):null}
async function saveCredential(token,pass){localStorage.setItem(CRED_KEY,await sealText(token,pass))}
function lockGh(){ghToken='';ghPass='';ghUnlocked=false;ghStateSha='';setGhStatus(localStorage.getItem(CRED_KEY)?'Private storage locked':'Private storage not set up','warn');render()}
async function unlockGh(pass){const c=localStorage.getItem(CRED_KEY);if(!c)throw Error('This device is not connected yet.');const token=await openText(c,pass);await checkToken(token);ghToken=token;ghPass=pass;ghUnlocked=true;setGhStatus('Private storage connected','ok');await reconcileGh()}
function setupGh(){openModal(`<h2>Connect private storage</h2><p class="sub">Paste the fine-grained GitHub token you created. It will be encrypted on this device before it is saved.</p><form id="ghSetup"><div class="form-grid"><div class="field full"><label>GitHub token</label><input name="token" type="password" autocomplete="off" required placeholder="github_pat_…"></div><div class="field"><label>Create Chip In HQ passphrase</label><input name="pass" type="password" minlength="10" autocomplete="new-password" required></div><div class="field"><label>Confirm passphrase</label><input name="again" type="password" minlength="10" autocomplete="new-password" required></div></div><div class="warning-box" style="margin-top:14px"><strong>Do not lose this passphrase.</strong> It is never stored in GitHub and is required to decrypt the private repository.</div><div class="form-actions"><button class="btn secondary" type="button" data-close-modal>Cancel</button><button class="btn gold" type="submit">Connect securely</button></div></form>`,true);document.getElementById('ghSetup').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),t=String(f.get('token')||'').trim(),p=String(f.get('pass')||''),a=String(f.get('again')||'');if(p!==a)return toast('Passphrases do not match');const btn=e.target.querySelector('[type=submit]');btn.disabled=true;btn.textContent='Checking…';try{await checkToken(t);await saveCredential(t,p);ghToken=t;ghPass=p;ghUnlocked=true;closeModal();await reconcileGh();render();toast('Private storage connected')}catch(err){btn.disabled=false;btn.textContent='Connect securely';toast(err.message)}}}
function unlockBox(){openModal(`<h2>Unlock Chip In HQ</h2><p class="sub">Enter your encryption passphrase to sync with the private ChipIn-Data repository.</p><form id="ghUnlock"><div class="field"><label>Passphrase</label><input name="pass" type="password" autocomplete="current-password" required autofocus></div><div class="form-actions"><button class="btn secondary" type="button" data-close-modal>Use local copy only</button><button class="btn gold" type="submit">Unlock</button></div></form>`);document.getElementById('ghUnlock').onsubmit=async e=>{e.preventDefault();const p=String(new FormData(e.target).get('pass')||''),b=e.target.querySelector('[type=submit]');b.disabled=true;b.textContent='Unlocking…';try{await unlockGh(p);closeModal();render();toast('Private storage unlocked')}catch(err){b.disabled=false;b.textContent='Unlock';toast(err.message)}}}
async function readCloudState(){const f=await getFile('data/chipin.enc');if(!f)return null;const x=JSON.parse(await openText(f.text,ghPass));if(x.format!=='ChipInHQState')throw Error('Private data format not recognised.');ghStateSha=f.sha;return x.state}
async function writeCloudState(){const cur=await getFile('data/chipin.enc');if(cur&&ghStateSha&&cur.sha!==ghStateSha){const other=JSON.parse(await openText(cur.text,ghPass)).state;if(Date.parse(other.updatedAt||0)>=Date.parse(state.updatedAt||0)){const c=await sealText(JSON.stringify({format:'ChipInConflict',savedAt:new Date().toISOString(),state}),ghPass);await putFile(`conflicts/${new Date().toISOString().replace(/[:.]/g,'-')}.enc`,c,'Preserve sync conflict');state=mergeDefaults(other,DEFAULT_STATE);await dbPut('app','state',state);ghStateSha=cur.sha;render();throw Error('A newer change from another device was loaded. Your local version was preserved in the encrypted conflicts folder.')}}const text=await sealText(JSON.stringify({format:'ChipInHQState',savedAt:new Date().toISOString(),state}),ghPass),r=await putFile('data/chipin.enc',text,'Sync Chip In HQ data',cur?.sha||'');ghStateSha=r.content?.sha||''}
async function syncReceipts(){let changed=false;for(const e of state.expenses||[]){if(!e.receiptName)continue;const blob=await dbGet('receipts',e.id);if(!blob)continue;const bytes=new Uint8Array(await blob.arrayBuffer()),h=await hashBytes(bytes);if(e.receiptHash===h&&e.cloudReceiptPath)continue;const safe=e.receiptName.replace(/[^a-z0-9._-]+/gi,'-').slice(-70),path=`receipts/${taxYearForDate(e.date).replace('/','-')}/${e.id}-${h.slice(0,12)}-${safe}.enc`;setGhStatus(`Archiving ${e.receiptName}…`);await putEncrypted(path,bytes,`Archive receipt ${e.receiptName}`);Object.assign(e,{receiptHash:h,cloudReceiptPath:path,receiptType:blob.type,receiptSize:bytes.length});changed=true}if(changed)await dbPut('app','state',state)}
async function syncGh(){if(!ghUnlocked||ghBusy)return;ghBusy=true;try{setGhStatus('Syncing encrypted data…');await syncReceipts();await writeCloudState();setGhStatus(`Synced · ${new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}`,'ok')}finally{ghBusy=false}}
function scheduleGh(){if(!ghUnlocked)return;clearTimeout(ghTimer);ghTimer=setTimeout(()=>syncGh().catch(e=>{console.error(e);setGhStatus('Sync needs attention','bad');toast(e.message)}),800)}
saveState=async()=>{await localSave();scheduleGh()};
async function reconcileGh(){const remote=await readCloudState();if(!remote){if(useful())await syncGh();else setGhStatus('Private storage connected · empty','ok');return}const r=Date.parse(remote.updatedAt||0),l=Date.parse(state.updatedAt||0);if(!useful()||r>l){state=mergeDefaults(remote,DEFAULT_STATE);await dbPut('app','state',state);render();setGhStatus('Loaded latest private data','ok')}else if(l>r)await syncGh();else setGhStatus('Private storage up to date','ok');await archivePendingInvoices()}
function invoiceSnap(inv){if(!inv.issuedSnapshot){const s=state.settings,c=clientById(inv.clientId)||{};inv.issuedSnapshot={capturedAt:new Date().toISOString(),business:{legalName:s.legalName,tradingName:s.tradingName,address:s.address,email:s.email,phone:s.phone,bankName:s.bankName,sortCode:s.sortCode,accountNumber:s.accountNumber,vatRegistered:s.vatRegistered,vatNumber:s.vatNumber},client:{name:c.name,contact:c.contact,address:c.address,email:c.email,phone:c.phone}}}return inv.issuedSnapshot}
function pdfBlob(inv){if(!window.jspdf)throw Error('PDF library did not load.');const {jsPDF}=window.jspdf,d=new jsPDF({unit:'mm',format:'a4'}),snap=invoiceSnap(inv),s=snap.business,c=snap.client,t=invoiceTotals(inv);try{if(LOGO_PDF_DATA_URL)d.addImage(LOGO_PDF_DATA_URL,'PNG',15,13,58,17)}catch{}d.setTextColor(10,47,87);d.setFontSize(24);d.setFont(undefined,'bold');d.text('INVOICE',195,22,{align:'right'});d.setFontSize(9);d.setFont(undefined,'normal');d.setTextColor(95,102,116);d.text(inv.number,195,28,{align:'right'});d.text(`Issued ${fmtDate(inv.issueDate)}   Due ${fmtDate(inv.dueDate)}`,195,33,{align:'right'});d.setDrawColor(220);d.line(15,40,195,40);d.setTextColor(23,32,51);d.setFont(undefined,'bold');d.text('FROM',15,49);d.text('BILL TO',110,49);d.setFont(undefined,'normal');d.text(`${s.legalName||''} trading as ${s.tradingName||'Chip In'}\n${s.address||''}\n${s.email||''}${s.phone?'\n'+s.phone:''}`,15,55,{maxWidth:80});d.text(`${c.name||''}${c.contact?'\n'+c.contact:''}${c.address?'\n'+c.address:''}${c.email?'\n'+c.email:''}`,110,55,{maxWidth:80});let y=88;d.setFillColor(244,246,250);d.rect(15,y,180,8,'F');d.setFont(undefined,'bold');d.text('Description',18,y+5.5);d.text('Qty',135,y+5.5,{align:'right'});d.text('Rate',165,y+5.5,{align:'right'});d.text('Amount',192,y+5.5,{align:'right'});d.setFont(undefined,'normal');y+=12;(inv.items||[]).forEach(x=>{const lines=d.splitTextToSize(x.description,105);d.text(lines,18,y);d.text(String(x.qty),135,y,{align:'right'});d.text(money(x.rate),165,y,{align:'right'});d.text(money(x.qty*x.rate),192,y,{align:'right'});y+=Math.max(8,lines.length*5+2)});y+=5;d.line(115,y,195,y);y+=7;d.text('Subtotal',145,y,{align:'right'});d.text(money(t.subtotal),192,y,{align:'right'});if(s.vatRegistered){y+=6;d.text(`VAT ${inv.vatRate}%`,145,y,{align:'right'});d.text(money(t.vat),192,y,{align:'right'})}y+=8;d.setFont(undefined,'bold');d.setFontSize(12);d.text('TOTAL',145,y,{align:'right'});d.text(money(t.total),192,y,{align:'right'});d.setFontSize(8.5);d.setFont(undefined,'normal');d.setTextColor(90,97,110);d.text(`Payment by bank transfer\nAccount name: ${s.bankName||''}\nSort code: ${s.sortCode||''}   Account number: ${s.accountNumber||''}`,15,260);if(inv.notes)d.text(d.splitTextToSize(inv.notes,75),110,260);return d.output('blob')}
async function archiveInvoice(inv){if(!ghUnlocked){inv.archivePending=true;await dbPut('app','state',state);return}const blob=pdfBlob(inv),bytes=new Uint8Array(await blob.arrayBuffer()),h=await hashBytes(bytes);if(inv.archiveHash===h&&inv.archivePath)return;const path=`invoices/${taxYearForDate(inv.issueDate).replace('/','-')}/${inv.number}.pdf.enc`;setGhStatus(`Archiving ${inv.number}…`);await putEncrypted(path,bytes,`Archive invoice ${inv.number}`);Object.assign(inv,{archivePath:path,archiveHash:h,archivedAt:new Date().toISOString(),archivePending:false});await localSave();await writeCloudState()}
async function archivePendingInvoices(){if(!ghUnlocked)return;for(const i of state.invoices||[]){const s=invoiceStatus(i);if(['Sent','Part paid','Paid','Overdue'].includes(s)&&(!i.archivePath||i.archivePending))await archiveInvoice(i)}}
markInvoiceSent=async id=>{const i=invoiceById(id);invoiceSnap(i);await baseMarkSent(id);try{await archiveInvoice(i);if(ghUnlocked)toast('Invoice sent and securely archived')}catch(e){i.archivePending=true;await localSave();toast('Invoice sent; archive will retry')}};
downloadInvoicePDF=async inv=>{try{if(inv.archivePath&&ghUnlocked){const bytes=await getEncrypted(inv.archivePath);if(bytes)return downloadBlob(new Blob([bytes],{type:'application/pdf'}),`${inv.number}.pdf`)}const b=pdfBlob(inv);downloadBlob(b,`${inv.number}.pdf`);if(ghUnlocked&&invoiceStatus(inv)!=='Draft'&&!inv.archivePath)archiveInvoice(inv).catch(console.error)}catch(e){baseDownloadPDF(inv)}};
downloadReceipt=async id=>{const e=expenseById(id);let b=await dbGet('receipts',id);if(!b&&e?.cloudReceiptPath&&ghUnlocked){try{const bytes=await getEncrypted(e.cloudReceiptPath);b=new Blob([bytes],{type:e.receiptType||'application/octet-stream'});await dbPut('receipts',id,b)}catch(err){return toast(err.message)}}if(b)return downloadBlob(b,e.receiptName||`receipt-${id}`);baseDownloadReceipt(id)};
function addGhSettings(){const host=document.getElementById('content');if(!host||document.getElementById('ghCard'))return;const c=document.createElement('div');c.id='ghCard';c.innerHTML=`<div class="section-title"><div><h2>Private cross-device storage</h2></div></div><div class="card"><div class="accent-bar"></div><h2>ChipIn-Data</h2><p class="muted">Business records, outgoings, prep blocks, issued invoice PDFs and receipts are encrypted before they leave this browser. The public ChipIn repository never receives your private records or token.</p><div class="hint-box"><strong>Repository:</strong> ${DATA_REPO}<br><strong>Status:</strong> <span id="ghSettingsStatus">${esc(ghStatus)}</span></div><div class="row-actions" style="justify-content:flex-start;margin-top:14px;flex-wrap:wrap">${!localStorage.getItem(CRED_KEY)?'<button class="btn gold" type="button" id="ghSetupBtn">Connect private storage</button>':ghUnlocked?'<button class="btn gold" type="button" id="ghSyncBtn">Sync now</button><button class="btn secondary" type="button" id="ghLockBtn">Lock</button>':'<button class="btn gold" type="button" id="ghUnlockBtn">Unlock</button>'}${localStorage.getItem(CRED_KEY)?'<button class="btn secondary" type="button" id="ghForgetBtn">Remove token from this device</button>':''}</div><div class="warning-box" style="margin-top:14px">Your encryption passphrase is not stored in GitHub. Keep it somewhere secure.</div></div>`;const danger=[...host.querySelectorAll('.section-title h2')].find(h=>h.textContent.trim()==='Danger zone')?.closest('.section-title');danger?danger.before(c):host.appendChild(c);document.getElementById('ghSetupBtn')?.addEventListener('click',setupGh);document.getElementById('ghUnlockBtn')?.addEventListener('click',unlockBox);document.getElementById('ghSyncBtn')?.addEventListener('click',()=>syncGh().then(()=>toast('Private storage synced')).catch(e=>toast(e.message)));document.getElementById('ghLockBtn')?.addEventListener('click',lockGh);document.getElementById('ghForgetBtn')?.addEventListener('click',()=>confirmAction('Remove the encrypted GitHub token from this device? Nothing in ChipIn-Data will be deleted.',async()=>{localStorage.removeItem(CRED_KEY);lockGh()}))}
renderSettings=function(){baseSettings();addGhSettings()};
function whenFree(fn,n=0){if(n>40)return;if(document.getElementById('modal')?.classList.contains('hidden'))return fn();setTimeout(()=>whenFree(fn,n+1),500)}
setTimeout(()=>{addGhBadge();if(localStorage.getItem(CRED_KEY)){setGhStatus('Private storage locked','warn');setTimeout(()=>whenFree(unlockBox),500)}else{setGhStatus('Private storage not set up','warn');setTimeout(()=>whenFree(setupGh),500)}},400);
