// Chip In HQ pricing defaults, client rates and sidebar contrast
const CHIPIN_JOB_CATEGORIES=['Events / hospitality','Quiz hosting','Website','Video editing','Production','General support','Other'];
const CHIPIN_RATE_DEFAULTS=Object.fromEntries(CHIPIN_JOB_CATEGORIES.map(c=>[c,{hourly:0,day:0}]));
Object.assign(DEFAULT_STATE.settings,{jobPrefix:'JOB',nextJobNumber:1});
DEFAULT_STATE.settings.categoryRates=DEFAULT_STATE.settings.categoryRates||CHIPIN_RATE_DEFAULTS;

const chipinStyle=document.createElement('style');
chipinStyle.textContent=`
.sidebar{background:#e6e8ec!important;color:#172033!important;border-right:1px solid #d4d8de}.brand-wrap{border-bottom-color:rgba(23,32,51,.12)!important}.brand-sub{color:#667080!important}.nav button{color:#4f5a6a!important}.nav button:hover,.nav button.active{background:#fff!important;color:#0a2f57!important;box-shadow:0 4px 14px rgba(23,32,51,.07)}.sidebar-foot{border-top-color:rgba(23,32,51,.12)!important}.ghost-btn{border-color:#c3c9d1!important;color:#253044!important;background:#f7f8fa!important}.save-state,.cloud-sync-state{color:#687282!important}.badge.quote{background:#f2edf9;color:#68459b}.calc-box{background:#f6f8fb;border:1px solid #dde3eb;border-radius:13px;padding:13px 14px}.calc-total{font-size:22px;font-weight:850;margin-top:3px}.calc-breakdown,.rate-source{font-size:11px;color:var(--muted);margin-top:4px}.discount-row.hidden-rate-field{display:none}.invoice-reference-strip{background:#f7f8fa;border:1px solid var(--line);border-radius:10px;padding:9px 11px;margin:12px 0 -12px;font-size:11px;color:#566071;display:flex;gap:18px;flex-wrap:wrap}@media(max-width:700px){.sidebar{border-right:0;border-top:1px solid #d4d8de!important}}`;
document.head.appendChild(chipinStyle);

function chipInNormaliseRateSettings(){
  state.settings.jobPrefix=state.settings.jobPrefix||'JOB';
  state.settings.nextJobNumber=Number(state.settings.nextJobNumber||1);
  state.settings.categoryRates=state.settings.categoryRates||{};
  for(const c of CHIPIN_JOB_CATEGORIES){const r=state.settings.categoryRates[c]||{};state.settings.categoryRates[c]={hourly:Number(r.hourly||0),day:Number(r.day||0)}}
}
function chipInNextJobReference(){chipInNormaliseRateSettings();const n=Number(state.settings.nextJobNumber||1),y=new Date().getFullYear(),prefix=(state.settings.jobPrefix||'JOB').trim()||'JOB';state.settings.nextJobNumber=n+1;return `${prefix}-${y}-${String(n).padStart(4,'0')}`}
let chipInRefBackfillSaving=false;
function chipInEnsureJobReferences(){chipInNormaliseRateSettings();let changed=false;for(const j of state.jobs||[]){if(!j.reference){j.reference=chipInNextJobReference();changed=true}}if(changed&&!chipInRefBackfillSaving){chipInRefBackfillSaving=true;saveState().catch(console.error).finally(()=>chipInRefBackfillSaving=false)}}
function chipInRateFor(clientId,category,type){chipInNormaliseRateSettings();const c=clientById(clientId),key=type==='hourly'?'hourlyRate':'dayRate',clientRate=Number(c?.[key]||0);if(clientRate>0)return{rate:clientRate,source:`Client agreed ${type==='hourly'?'hourly':'day'} rate`};const preset=Number(state.settings.categoryRates?.[category]?.[type]||0);if(preset>0)return{rate:preset,source:`${category} preset`};return{rate:0,source:'No preset — enter a rate for this job'}}
function chipInJobAmount(v){const rate=Number(v.rate||0),discount=Math.max(0,Number(v.discount||0)),qty=v.rateType==='hourly'?(Math.max(0,Number(v.hours||0))+Math.max(0,Number(v.minutes||0))/60):Math.max(0,Number(v.days||0)),subtotal=rate*qty,override=v.overrideAmount;return override!==''&&override!==null&&override!==undefined?Math.max(0,Number(override||0)):Math.max(0,subtotal-discount)}
function chipInBasisText(j){if(!j.rateType)return'';if(j.overrideAmount!==null&&j.overrideAmount!==undefined&&j.overrideAmount!=='')return'Price overridden for this job';const q=j.rateType==='hourly'?`${Number(j.hours||0)}h ${Number(j.minutes||0)}m`:`${Number(j.days||0)} day${Number(j.days||0)===1?'':'s'}`;return `${q} × ${money(j.rate||0)}${Number(j.discount||0)>0?` · ${money(j.discount)} discount`:''}`}

const chipInBaseStatusBadge=statusBadge;
statusBadge=function(s){return s==='Quote'?'<span class="badge quote">Quote</span>':chipInBaseStatusBadge(s)};

clientForm=function(c={}){return `<h2>${c.id?'Edit':'New'} client</h2><p class="sub">Save a client once, then reuse their details and agreed rates on jobs and invoices.</p><form id="clientForm"><div class="form-grid"><div class="field"><label>Business / client name</label><input name="name" required value="${esc(c.name||'')}"></div><div class="field"><label>Contact name</label><input name="contact" value="${esc(c.contact||'')}"></div><div class="field"><label>Email</label><input type="email" name="email" value="${esc(c.email||'')}"></div><div class="field"><label>Phone</label><input name="phone" value="${esc(c.phone||'')}"></div><div class="field full"><label>Invoice address</label><textarea name="address">${esc(c.address||'')}</textarea></div><div class="field"><label>Agreed hourly rate (£)</label><input name="hourlyRate" type="number" min="0" step="0.01" value="${Number(c.hourlyRate||0)||''}" placeholder="Optional"></div><div class="field"><label>Agreed day rate (£)</label><input name="dayRate" type="number" min="0" step="0.01" value="${Number(c.dayRate||0)||''}" placeholder="Optional"></div><div class="field full"><div class="hint-box">Client rates take priority over category presets. You can still change the rate, add a discount or override the final price on an individual job.</div></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(c.notes||'')}</textarea></div></div><div class="form-actions"><button class="btn secondary" type="button" data-close-modal>Cancel</button><button class="btn" type="submit">Save client</button></div></form>`};
openClientForm=function(id){const c=id?clientById(id):{};openModal(clientForm(c));$('#clientForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target).entries());v.hourlyRate=Number(v.hourlyRate||0);v.dayRate=Number(v.dayRate||0);if(c.id)Object.assign(c,v);else state.clients.push({id:uid('cli'),...v,createdAt:new Date().toISOString()});await saveState();closeModal();render()}};